name: Build & test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain with caching
        uses: brndnmtthws/rust-action@v1
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - run: cargo build
      - run: cargo test
        env:
          RUST_BACKTRACE: 1
